config/routes.rb
Tap::Application.routes.draw do
  
  # web application routes 
  root :to => "home#index"

  #devise routes for authenticating users
  devise_for :users, :controllers => { :registrations => "registrations" }
  # general routes for managing users
  resources :users
  # a profile route so users can see their profile
  match "profile" => "users#show"

  # routes for static pages - content controller - just add view for action name  
  get 'content/:action' => 'content'
  get 'content/press-releases/2011-03-12' => "content#press-release1"
  get 'content/career-opportunities/:action' => 'content'
  
  #event routes
  match "/events/:id/checkin" => "events#checkin", :as => 'event_checkin'
  match "/events/:id/checkout" => "events#checkout", :as => 'event_checkout'
  get "/events/new_wizard" => "events#new_wizard", :as => 'wizard_new_event'
  post "/events/place_list" => "events#place_list"
  resources :events

  #place routes
  match "/places/checkin/:id" => "places#checkin", :as => 'checkin'
  match "/places/checkout" => "places#checkout", :as => 'checkout'
  match "/places/search" => "places#search", :as => 'search_places'
  match "/places/searchresults" => "places#searchresults"
  get "/places/quick_add" => "places#quickadd", :as => 'quick_add_place'
  resources :places

  # Route for documenting the API 
  get "/api" => "api#index"

  # API routes
  scope "/api/v11", :format => :json do
    root :to => "api#v11", :as => 'v11_documentation', :format => :html
    # For now all of these are posts with an email and password. If we had time we should upgrade to using basic authentication and then making some of these gets and other posts based on whether they change the state of the app
    match "/login" => "api#login" # Log in - this is really just a hook for down the line if/when we move to basic auth. Right now, you can call login, but all it really does is confirm whether or not the email and password are valid
    match "/places" => "api#places" # Get a list of places near a latlng
    match "/place/:id" => "api#placeshow" # Get info on a place
    match "/placecreate" => "api#placecreate" # Add a new place
    match "/events" => "api#events" # Get a list of events near a latlng
    match "/event/:id" => "api#eventshow" # Get info on an event
    match "/eventcreate" => "api#eventcreate" # Add a new event
    match "/place/:id/checkin" => "api#placecheckin" # Check in to a place
    match "/place/:id/checkout" => "api#placecheckout" # Check out of a place
    match "/place/:id/matches" => "api#placematches" # Get matches for a given place
    match "/event/:id/checkin" => "api#eventcheckin" # Check in to an event
    match "/event/:id/checkout" => "api#eventcheckout" # Check out of an event
    match "/event/:id/matches" => "api#eventmatches" # Get matches for a given event
    
    # Match routes
    match "/match/:id" => "api#match" # Get info on a specific user match 

    # Places/events
    match "/checkins" => "api#places_events" # Get a list of places and events near a lat/lng

  end
  
end

app/models/event.rb
class Event < ActiveRecord::Base

  CATEGORIES = ['Convention','Conference','Trade Show','Networking Event','Seminar','Networking Group','Charity Event','Other']  

  acts_as_mappable

  include Checkinable
  include Truncatable
  
  has_attached_file :logo,
        :storage => :s3,
        :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",
        :default_url => "http://tap.heroku.com/api/images/calendar.png",
        :path => "/event_logo/:style/:filename"

  has_many :users
  belongs_to :place
  belongs_to :creator, :class_name => "User"
  
  
  def self.near(lat, lng)
    self.within(0.5, :origin => [lat,lng]).order('distance')
  end

  def category_name
    if category
      "(#{Event::CATEGORIES[category.to_i]})"
    end
  end

  def distance_away
    "#{(distance.to_f * 5280).round} ft" rescue nil
  end

  def pretty_ends_at
    self.end.to_formatted_s(:long) if self.end.present?
  end

  def pretty_starts_at
    self.start.to_formatted_s(:long) if self.start.present?
  end
  
  def short_address
    self.place.address.truncate(25, :separator => ' ') rescue nil
  end
  
  def logo_url
    self.logo.url
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # GET /events/new
  def new
    @event = Event.new
  end

  def new_wizard
    @event = Event.new
  end

  # POST /events
  def create
    @event = Event.new(params[:event])
    @place = @event.place
    @event.lat = @place.lat
    @event.lng = @place.lng
    @event.creator = current_user
    if @event.save
     redirect_to(place_path(@event.place), :notice => 'Event was successfully created.')
    else
       render :action => "new" 
    end
  end

  # GET /events/1
  def show
    @event = Event.find(params[:id])
    @place = @event.place
  end

  def checkin
    @event = Event.find(params[:id])
    @event.checkin(current_user)
    flash[:notice] = "Congratulations #{@current_user.name}. You successfully checked in to #{@event.name}. There are #{@event.users(true).count - 1} other users there."
    redirect_to(event_path(@event))
  end

  def checkout
    @event = Event.find(params[:id])
    @event.checkout(current_user)
    flash[:notice] = "Congratulations #{@current_user.name}. You successfully checked out of #{@event.name}. There are #{@event.users(true).count} other users there."
    redirect_to(event_path(@event))
  end

  def place_list
    @location = Location.new(params[:address], params[:address_2], params[:city], params[:state], params[:zip])
    @places = Place.near(@location.lat, @location.lng)
  end

# Scaffolded methods

  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for (@event, :html => { :multipart => true }) do |f|

	-if @event.errors.any?
		#error_explanation
			%h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
			%ul
				- @event.errors.full_messages.each do |msg|
					%li= msg

	.field
		= f.hidden_field :place_id, :value => params[:place_id]
	
	.field
		= f.label :name
		= f.text_field :name
	
	.field
		= f.label :start
		= f.datetime_select :start
	
	.field
		= f.label :end
		= f.datetime_select :end
	
	.field
		= f.label :category
		= select(:event, :category, Event::CATEGORIES.collect {|i| [i, Event::CATEGORIES.index(i)]})

	.field
		= f.label :logo
		%br/
		- if @event.logo_file_name
			= image_tag @event.logo.url, :width => "100"
			%br/
		= f.file_field :logo

	.field
		= f.label :url
		= f.text_field :url

	.field
		= f.label :phone
		= f.text_field :phone

	.field
		= f.label :email
		= f.text_field :email

	.field
		= f.label :description
		= f.text_area :description

	.field
		= f.check_box :organizer
		Are you the organizer?

	.actions
		= f.submit 'Save'
		

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table
  %tr
    %th Name
    %th Start
    %th End
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= event.name
      %td= event.start
      %td= event.end
      %td= link_to 'Show', event
      %td= link_to 'Edit', edit_event_path(event)
      %td= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1
	add 
	%span.subhead events

= render 'form'

= link_to 'Back', events_path

app/views/events/new_wizard.html.haml
%h1
	add 
	%span.subhead events

%p Enter an address for the new event:

= form_tag('/events/place_list', :class =>"add-events") do
	.field
		= label_tag :address
		= text_field_tag :address

	.field
		= label_tag :city
		= text_field_tag :city

	.field
		= label_tag :state
		= text_field_tag :state, nil, :class => "state"

	.field
		= label_tag :zip
		= text_field_tag :zip, nil, :class => "zip"

	%div.hr
	%div.actions= image_submit_tag "/images/template/enter-address.png", :name =>"commit", :value => "Find Events"

app/views/events/place_list.html.haml
%h1 Add Event

%p
	Address:
	%br/
	=@location.address
	%br/
	=@location.city + ', ' + @location.state + ' ' + @location.zip
	%br/

%h2 Places

%p 
	If your event is in one of the following venues, add it to the venue. Otherwise, click here to 
	=link_to "add a place", "#{quick_add_place_path()}?place[address]=#{@location.address}&place[city]=#{@location.city}&place[state]=#{@location.state}&place[postcode]=#{@location.zip}"



%ul
	- for place in @places
		%li 
			#{place.name}, #{place.category_name} #{place.address}.
			=link_to "Add event here", "/events/new?place_id=#{place.id}"
	

app/views/events/show.html.haml
%h1 Event

%p#notice= notice
	
%p
	%b Name:
	= @event.name

%p
	%b Location:
	= @place.name

%p
	%b Address:
	= @place.address

%p
	%b Category:
	= @event.category_name

- if @event.logo_file_name
	%p
		%b Logo:
		= image_tag @event.logo.url, :width => "100"

%p
	%b URL:
	= @event.url

%p
	%b Phone:
	= @event.phone

%p
	%b Email:
	= @event.email

%p
	%b Description:
	= @event.description

%p
	%b Producer Name:
	= @event.producer_name


%h2 
	Checked in users 
	= "(#{@event.users.count} users)"

- if (@event.users.include? current_user)
	%p
		%b 
			you are checked in
			= link_to 'Check out', event_checkout_path(@event)
- else
	%p
		%b you are NOT checked in
		= link_to 'Check in', event_checkin_path(@event)

- for user in @event.users
	%li= user.name 

- if (@event.users.include? current_user)
	%h2 Matching users

	- for user in @event.matches(current_user)
		%li #{user.name} (#{user.match_reasons})