config/routes.rb
Tap::Application.routes.draw do
  
  # web application routes 
  root :to => "home#index"

  #devise routes for authenticating users
  devise_for :users, :controllers => { :registrations => "registrations" }
  # general routes for managing users
  resources :users
  # a profile route so users can see their profile
  match "profile" => "users#show"

  # routes for static pages - content controller - just add view for action name  
  get 'content/:action' => 'content'
  get 'content/press-releases/2011-03-12' => "content#press-release1"
  get 'content/career-opportunities/:action' => 'content'
  
  #event routes
  match "/events/:id/checkin" => "events#checkin", :as => 'event_checkin'
  match "/events/:id/checkout" => "events#checkout", :as => 'event_checkout'
  get "/events/new_wizard" => "events#new_wizard", :as => 'wizard_new_event'
  post "/events/place_list" => "events#place_list"
  resources :events

  #place routes
  match "/places/checkin/:id" => "places#checkin", :as => 'checkin'
  match "/places/checkout" => "places#checkout", :as => 'checkout'
  match "/places/search" => "places#search", :as => 'search_places'
  match "/places/searchresults" => "places#searchresults"
  get "/places/quick_add" => "places#quickadd", :as => 'quick_add_place'
  resources :places

  # Route for documenting the API 
  get "/api" => "api#index"

  # API routes
  scope "/api/v11", :format => :json do
    root :to => "api#v11", :as => 'v11_documentation', :format => :html
    # For now all of these are posts with an email and password. If we had time we should upgrade to using basic authentication and then making some of these gets and other posts based on whether they change the state of the app
    match "/login" => "api#login" # Log in - this is really just a hook for down the line if/when we move to basic auth. Right now, you can call login, but all it really does is confirm whether or not the email and password are valid
    match "/places" => "api#places" # Get a list of places near a latlng
    match "/place/:id" => "api#placeshow" # Get info on a place
    match "/placecreate" => "api#placecreate" # Add a new place
    match "/events" => "api#events" # Get a list of events near a latlng
    match "/event/:id" => "api#eventshow" # Get info on an event
    match "/eventcreate" => "api#eventcreate" # Add a new event
    match "/place/:id/checkin" => "api#placecheckin" # Check in to a place
    match "/place/:id/checkout" => "api#placecheckout" # Check out of a place
    match "/place/:id/matches" => "api#placematches" # Get matches for a given place
    match "/event/:id/checkin" => "api#eventcheckin" # Check in to an event
    match "/event/:id/checkout" => "api#eventcheckout" # Check out of an event
    match "/event/:id/matches" => "api#eventmatches" # Get matches for a given event
    
    # Match routes
    match "/match/:id" => "api#match" # Get info on a specific user match 

    # Places/events
    match "/checkins" => "api#places_events" # Get a list of places and events near a lat/lng

  end
  
end

app/models/place.rb
class Place < ActiveRecord::Base

  CATEGORIES = ['Convention Center','Conference Center','Event Space','Public Space','Restaurant','Other']  

  acts_as_mappable
  
  include Checkinable
  include Truncatable
  
  has_many :users
  has_many :events
  
  def self.near(lat, lng)
    self.within(0.5, :origin => [lat,lng]).order('distance')
  end

  def category_name
    if category
      "(#{Place::CATEGORIES[category.to_i]})"
    end
  end

  def distance_away
    "#{(distance.to_f * 5280).round} ft" rescue nil
  end

  def full_address
    "#{self.address}, #{self.city}, #{self.state} #{self.postcode}"
  end
  
  def short_address
    self.address.truncate(25, :separator => ' ') rescue nil
  end
  

  def geocode
      latlng = GeoKit::Geocoders::GoogleGeocoder.geocode("#{self.full_address}")
      self.lat = latlng.lat
      self.lng = latlng.lng
  end
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def checkin
    @place = Place.find(params[:id])
    @place.checkin(current_user)
    flash[:notice] = "Congratulations #{@current_user.name}. You successfully checked in to #{@place.name}. There are #{@place.users(true).count - 1} other users there."
    redirect_to(place_path(@place))
  end

  def checkout
    @place = Place.find(params[:id])
    @place.checkout(current_user)
    flash[:notice] = "Congratulations #{@current_user.name}. You successfully checked out of #{@place.name}. There are #{@place.users(true).count} other users there."
    redirect_to(place_path(@place))
  end

  # POST /places
  def create
    @place = Place.new(params[:place])
    @place.geocode
    if @place.save
      redirect_to(@place, :notice => "Place was successfully created.")
    else
      render :action => "new"
    end
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  def quickadd
    @place = Place.new(params[:place])
  #  @place.address = params['address']
  end

  def search
  end

  def searchresults
    @location = Location.new(params[:address], '', params[:city], params[:state], params[:zip])
    @places = Place.near(@location.lat, @location.lng)
    @events = Event.near(@location.lat, @location.lng)
  end

  def show
    @place = Place.find(params[:id])    
  end

  # Scaffolded code to review
  

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # PUT /places/1
  # PUT /places/1.xml
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to(@place, :notice => 'Place was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.xml
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to(places_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.haml
= form_for @place do |f|
	-if @place.errors.any?
		#error_explanation
		%h2= "#{pluralize(@place.errors.count, "error")} prohibited this place from being saved:"
		%ul
			- @place.errors.full_messages.each do |msg|
				%li= msg

	.field
		= f.label :name
		= f.text_field :name

	.field
		= f.label :category
		= select(:place, :category, Place::CATEGORIES.collect {|i| [i, Place::CATEGORIES.index(i)]})
	
	.field
		= f.label :address
		= f.text_field :address
	
	.field
		= f.label :city
		= f.text_field :city
	
	.field
		= f.label :state
		= f.text_field :state, :class => "state"
	
	.field
		= f.label :phone
		= f.text_field :phone, :class => "phone"
		
	.field
		= f.label :postcode, "Zip"
		= f.text_field :postcode, :class => "zip"
	
	.field
		= f.label :href
		= f.text_field :href

	%div.hr
	%div.actions= image_submit_tag "/images/template/save.png", :name =>"commit", :value => "Save"

app/views/places/edit.html.haml
%h1 Editing place

= render 'form'

= link_to 'Show', @place
\|
= link_to 'Back', places_path

app/views/places/index.html.haml
%h1 Listing places

%table
  %tr
    %th Name
    %th Address
    %th City
    %th State
    %th Country
    %th Phone
    %th Href
    %th Postcode
    %th Owner
    %th Uuid
    %th
    %th
    %th

  - @places.each do |place|
    %tr
      %td= place.name
      %td= place.address
      %td= place.city
      %td= place.state
      %td= place.country
      %td= place.phone
      %td= place.href
      %td= place.postcode
      %td= place.owner
      %td= place.uuid
      %td= link_to 'Show', place
      %td= link_to 'Edit', edit_place_path(place)
      %td= link_to 'Destroy', place, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Place', new_place_path

app/views/places/new.html.haml
%h1
	add 
	%span.subhead places

= render 'form'

= link_to 'Back', places_path

app/views/places/quickadd.html.haml
= form_for @place do |f|
	-if @place.errors.any?
		#error_explanation
		%h2= "#{pluralize(@place.errors.count, "error")} prohibited this place from being saved:"
		%ul
			- @place.errors.full_messages.each do |msg|
				%li= msg

	.field
		= f.label :name
		= f.text_field :name

	.field
		= f.label :category
		= select(:place, :category, Place::CATEGORIES.collect {|i| [i, Place::CATEGORIES.index(i)]})
	
	.field
		= f.label :phone
		= f.text_field :phone
	
	.field
		= f.label :href
		= f.text_field :href
	
	.field
		= f.hidden_field :address

	.field
		= f.hidden_field :city

	.field
		= f.hidden_field :state

	.field
		= f.hidden_field :postcode

	
	.actions
		= f.submit 'Save'

app/views/places/search.html.haml
%h1
	find 
	%span.subhead events

= form_tag('/places/searchresults', :class =>"find-events") do

	.field
		= label_tag :address
		= text_field_tag :address

	.field
		= label_tag :city
		= text_field_tag :city

	.field
		= label_tag :state
		= text_field_tag :state, nil, :class => "state"

	.field
		= label_tag :zip
		= text_field_tag :zip, nil, :class => "zip"

	%div.hr
	%div.actions= image_submit_tag "/images/template/find-events.png", :name =>"commit", :value => "Find Events"

app/views/places/searchresults.html.haml
%h1 Location

%p
	Address:
	%br/
	=@location.address + @location.address_2 
	%br/
	=@location.city + ', ' + @location.state + ' ' + @location.zip
	%br/
	Latlng:
	=@location.lat 
	=@location.lng

%h2 Places

%p=link_to "Add a place", new_place_path()

%p
	Number of places
	= @places.length		
%ul
	- for place in @places
		%li 
			#{place.name}, #{place.category_name} #{place.address}. #{place.distance_away}
			=link_to "Check in", checkin_path(place)
			=link_to "View", place_path(place)
	
%h2 Events
%p
	Number of events
	= @events.length		
%ul
	- for event in @events
		%li 
			#{event.name} #{event.category_name} #{event.distance_away}
			=link_to "Check in", event_checkin_path(event)
			=link_to "View", event_path(event)

app/views/places/show.html.haml
%h1 Place

%p#notice= notice
	
%p
	%b Name:
	= @place.name
%p
	%b Address:
	= @place.address

%h2 
	Checked in users 
	= "(#{@place.users.count} users)"

- if (@place.users.include? current_user)
	%p
		%b 
			you are checked in
			= link_to 'Check out', checkout_path(:id => @place)
- else
	%p
		%b you are NOT checked in
		= link_to 'Check in', checkin_path(:id => @place)

- for user in @place.users
	%li= user.name 

- if (@place.users.include? current_user)
	%h2 Matching users

- for user in @place.matches(current_user)
	%li #{user.name} (#{user.match_reasons})

%h2 Events

- if !@place.events.empty?
	There are #{@place.events.length} events scheduled at #{@place.name}
	%ul
	- for event in @place.events
		%li= link_to event.name, event_path(:id => event)

- else
	%p There are no events scheduled at this place

%p= link_to 'Add an event', new_event_path(:place_id => @place)
 