config/routes.rb
Tap::Application.routes.draw do
  
  # web application routes 
  root :to => "home#index"

  #devise routes for authenticating users
  devise_for :users, :controllers => { :registrations => "registrations" }
  # general routes for managing users
  resources :users
  # a profile route so users can see their profile
  match "profile" => "users#show"

  # routes for static pages - content controller - just add view for action name  
  get 'content/:action' => 'content'
  get 'content/press-releases/2011-03-12' => "content#press-release1"
  get 'content/career-opportunities/:action' => 'content'
  
  #event routes
  match "/events/:id/checkin" => "events#checkin", :as => 'event_checkin'
  match "/events/:id/checkout" => "events#checkout", :as => 'event_checkout'
  get "/events/new_wizard" => "events#new_wizard", :as => 'wizard_new_event'
  post "/events/place_list" => "events#place_list"
  resources :events

  #place routes
  match "/places/checkin/:id" => "places#checkin", :as => 'checkin'
  match "/places/checkout" => "places#checkout", :as => 'checkout'
  match "/places/search" => "places#search", :as => 'search_places'
  match "/places/searchresults" => "places#searchresults"
  get "/places/quick_add" => "places#quickadd", :as => 'quick_add_place'
  resources :places

  # Route for documenting the API 
  get "/api" => "api#index"

  # API routes
  scope "/api/v11", :format => :json do
    root :to => "api#v11", :as => 'v11_documentation', :format => :html
    # For now all of these are posts with an email and password. If we had time we should upgrade to using basic authentication and then making some of these gets and other posts based on whether they change the state of the app
    match "/login" => "api#login" # Log in - this is really just a hook for down the line if/when we move to basic auth. Right now, you can call login, but all it really does is confirm whether or not the email and password are valid
    match "/places" => "api#places" # Get a list of places near a latlng
    match "/place/:id" => "api#placeshow" # Get info on a place
    match "/placecreate" => "api#placecreate" # Add a new place
    match "/events" => "api#events" # Get a list of events near a latlng
    match "/event/:id" => "api#eventshow" # Get info on an event
    match "/eventcreate" => "api#eventcreate" # Add a new event
    match "/place/:id/checkin" => "api#placecheckin" # Check in to a place
    match "/place/:id/checkout" => "api#placecheckout" # Check out of a place
    match "/place/:id/matches" => "api#placematches" # Get matches for a given place
    match "/event/:id/checkin" => "api#eventcheckin" # Check in to an event
    match "/event/:id/checkout" => "api#eventcheckout" # Check out of an event
    match "/event/:id/matches" => "api#eventmatches" # Get matches for a given event
    
    # Match routes
    match "/match/:id" => "api#match" # Get info on a specific user match 

    # Places/events
    match "/checkins" => "api#places_events" # Get a list of places and events near a lat/lng

  end
  
end

app/views/layouts/_footer.html.erb
<div class="copy">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed faucibus. Nam a felis et eros condimentum placerat. Integer non ante quis diam luctus suscipit. Maecenas mi mauris, ullamcorper ut, ullamcorper sit amet, elementum sed, purus. Pellentesque lobortis, nibh sit amet tristique fringilla, sem velit ultricies turpis, nec cursus sapien nibh at neque. Nam sapien dolor, dapibus vitae, pellentesque quis, dignissim eget, metus. Etiam eu justo ut massa lobortis bibendum. Integer massa purus, fringilla et, pharetra sed, consequat ut, diam. Fusce lorem. Praesent at diam varius elit placerat lobortis. Ut vitae magna vitae sapien adipiscing gravida. Maecenas eu dolor in libero tempus viverra. Proin diam tellus, ultrices ullamcorper, venenatis tristique, pretium vitae, orci. Nunc mauris. Nam vulputate dui id quam. Nullam rutrum convallis turpis.</div> 
  
<div class="text-links"><a href="/content/about-us">about us</a> | <a href="/content/contact-us">contact us</a> | <a href="/content/career-opportunities">career opportunities</a> | <a href="/content/press-releases">press releases</a> | <a href="/content/advertising-opportunities">advertising opportunities</a> | <a href="/content/privacy-policy">privacy policy</a> | <a href="/content/terms-of-use">terms of use</a></div> 
	<div class="copyright">herematch &copy; 2011. All Rights Reserved.<br /> 
</div>

app/views/layouts/_topbar_logged_in.html.erb
<div class="greeting"> 
	Hello <%= current_user.first_name %>. Not <%= current_user.first_name %>, <%= link_to('Log Out', destroy_user_session_path) %> 
</div>
<div class="navigation"> 
	<ul id="MenuBar1" class="MenuBarHorizontal"> 
		<li><%= link_to('view profile', user_path(current_user)) %></li> 
		<li><%= link_to('edit profile', edit_user_path(current_user)) %></li> 
		<li><%= link_to('add places', new_place_path) %></li> 
		<li><%= link_to('add events', wizard_new_event_path) %></li> 
		<li><%= link_to('find events', search_places_path) %></li> 
	</ul> 
</div>

app/views/layouts/_topbar_visitor.html.erb
<div class="login-form"> 
<%= form_for("user", :url => user_session_path) do |f| %>
	<div class="text-field-name">Email:</div> 
	<div class="text-field"><%= f.text_field :email%></div> 
	<div class="text-field-name">Password:</div> 
	<div class="text-field"><%= f.password_field :password%></div> 
	<div class="log-in-button"><input type="image" src="/images/template/login.png" border="0" alt="Submit Form" /></div> 
<% end %>
</div> 
<div class="navigation"> 
	<ul id="MenuBar1" class="MenuBarHorizontal"> 
		<li><a href="/">home</a></li> 
		<li><a href="/content/app-features">app features</a></li> 
		<li><%= link_to 'sign up', root_path %></li> 
	</ul> 
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml">
<head> 
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
	<title>herematch</title> 
	<link rel="shortcut icon" type="image/x-icon" href="/images/template/favicon.ico">	
	<%= stylesheet_link_tag :all %>
	<%= javascript_include_tag :defaults %>
	<%= csrf_meta_tag %>
</head> 

<body> 
<div class="background-gradient"> 
	<div class="header"> 
		<div class="logo"><a href="/"><img src="/images/template/herematch-logo.png" alt="Here Match" width="341" height="94" /></a></div>
		<% if user_signed_in? %>
			<%= render "layouts/topbar_logged_in" %>
		<% else %>
			<%= render "layouts/topbar_visitor" %>
		<% end %>
	</div> 

	<div class="line"></div> 

	<div class="content">
	
		<%= alert %>

		<%= yield %>

	</div> 
</div> 

<div class="footer"> 
	<%= render "layouts/footer"%>
</div> 

<script type="text/javascript"> 
var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"/images/spry/SpryMenuBarDownHover.gif", imgRight:"/images/spry/SpryMenuBarRightHover.gif"});
</script> 
</body> 
</html>